title: Parchment
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://peon-pasado.github.io"
baseurl: "/do-panic"

footer_only_homepage: true
footer_url: "https://github.com/peon-pasado"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://pro-panda.github.io/resume.pdf"
