title: DO PANIC
author: Bashca
subtitle: just be here now

url: "https://peon-pasado.github.io"
baseurl: "/do-panic"

footer_only_homepage: true
footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Codeforces"
   absolute-link: "https://codeforces.com/profile/Bashca"

plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
katex:
  js_path: "assets"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: false      # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"  # errorColor